PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata VALUES('en_US');
CREATE TABLE `pronounce_table` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `audio_uri` TEXT NOT NULL, `global_id` BLOB, `global_owner` TEXT);
CREATE TABLE `phrase_table` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `phrase` TEXT NOT NULL, `definition` TEXT, `lang` TEXT NOT NULL, `id_pronounce` INTEGER, `id_image` INTEGER, `time_change` INTEGER NOT NULL, `like` INTEGER NOT NULL, `dislike` INTEGER NOT NULL, `global_id` BLOB, `global_owner` TEXT);
CREATE TABLE `images_table` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `img_uri` TEXT NOT NULL, `global_id` BLOB, `global_owner` TEXT);
CREATE TABLE `cards_table` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `id_phrase` INTEGER NOT NULL, `id_translate` INTEGER NOT NULL, `id_image` INTEGER, `reason` TEXT NOT NULL, `time_change` INTEGER NOT NULL, `like` INTEGER NOT NULL, `dislike` INTEGER NOT NULL, `global_id` BLOB, `global_owner` TEXT, FOREIGN KEY(`id_phrase`) REFERENCES `phrase_table`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`id_translate`) REFERENCES `phrase_table`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE TABLE `settings` (`key` TEXT NOT NULL, `value` TEXT, PRIMARY KEY(`key`));
CREATE TABLE `modules` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NOT NULL, `owner` TEXT NOT NULL, `time_change` INTEGER NOT NULL, `like` INTEGER NOT NULL, `dislike` INTEGER NOT NULL, `global_id` BLOB, `global_owner` TEXT);
CREATE TABLE `module_card` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `id_module` INTEGER NOT NULL, `id_card` INTEGER NOT NULL, `global_id` BLOB, `global_owner` TEXT, FOREIGN KEY(`id_module`) REFERENCES `modules`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`id_card`) REFERENCES `cards_table`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE TABLE `error_card` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `id_phrase` INTEGER NOT NULL, `id_translate` INTEGER NOT NULL, `correct` INTEGER NOT NULL, `incorrect` INTEGER NOT NULL, `percent_correct` INTEGER NOT NULL, FOREIGN KEY(`id_phrase`) REFERENCES `phrase_table`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`id_translate`) REFERENCES `phrase_table`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE TABLE `users_table` (`global_id` TEXT NOT NULL, `name` TEXT NOT NULL, PRIMARY KEY(`global_id`));
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT INTO room_master_table VALUES(42,'bbe8245ebae4104a12466f50513b9afa');
DELETE FROM sqlite_sequence;
CREATE UNIQUE INDEX `index_cards_table_id_phrase_id_translate` ON `cards_table` (`id_phrase`, `id_translate`);
CREATE UNIQUE INDEX `index_module_card_id_module_id_card` ON `module_card` (`id_module`, `id_card`);
CREATE UNIQUE INDEX `index_error_card_id_phrase_id_translate` ON `error_card` (`id_phrase`, `id_translate`);
COMMIT;