package com.uogames.flags

enum class Languages(val language: String, val isoCode: String) {
	ABKHAZIAN("Apsua byzshwa", "ab"),
	AFAR("Qafar af", "aa"),
	AFRIKAANS("Afrikaans", "af"),
	AKAN("Ákán", "ak"),
	ALBANIAN("shqip", "sq"),
	ALGERIAN_ARABIC("دزيرية","arq"),
	AMHARIC("አማርኛ", "ar"),
	ARABIC("اَلْعَرَبِيَّةُ", "ar"),
	ARAGONESE("aragonés", "an"),
	ARMENIAN("հայերէն", "hy"),
	ASSAMESE("অসমীয়া", "as"),
	AVARIC("მაღარულ მაწ", "av"),
	AYMARA("Aymar aru", "ay"),
	AZERBAIJANI("Azeri", "az"),
	BAMBARA("Bámánánkán", "bm"),
	BASHKIR("Башҡортса", "ba"),
	BASQUE("euskara", "eq"),
	BELARUSIAN("Беларуская мова", "be"),
	BENGALI("বাংলা", "bn"),
	BERBER("ⵜⴰⵎⴰⵣⵉⵖⵜ, ⵜⵎⵣⵗⵜ","ber"),
	BISLAMA("Bislama", "bi"),
	BOSNIAN("bosanski", "bs"),
	BRETON("brezhoneg", "br"),
	BULGARIAN("български", "bg"),
	BURMESE("မြန်မာစာ", "my"),
	CATALAN("català", "ca"),
	CHAMORRO("Finuʼ Chamoru", "ch"),
	CHECHEN("Noxçiyn mott", "ce"),
	CHEWA("Nyanja", "ny"),
	CHINESE("汉语", "zh"),
	CHUVASH("Čăvašla", "cv"),
	CORNISH("Kernewek", "kw"),
	CORSICAN("corsu", "co"),
	CREE("ᓀᐦᐃᔭᐍᐏᐣ", "cr"),
	CROATIAN("hrvatski", "hr"),
	CZECH("čeština", "cs"),
	DANISH("dansk", "da"),
	DARI("دری","prs"),
	DIVEHI("ދިވެހި", "dv"),
	DUTCH("Nederlands", "nl"),
	DZONGKHA("རྫོང་ཁ་", "dz"),
	ENGLISH("English", "en"),
	ESPERANTO("Esperanto", "eo"),
	ESTONIAN("eesti keel", "et"),
	EWE("Eʋegbe", "ee"),
	FAROESE("føroyskt mál", "fo"),
	FIJIAN("Vosa vaka-Viti", "fj"),
	FINNISH("suomen kieli", "fi"),
	FRENCH("français", "fr"),
	FRISIAN("Frysk", "fy"),
	FULAH("Fulani", "ff"),
	GAELIC("Gàidhlig", "gd"),
	GALICIAN("galego", "gl"),
	GANDA("Oluganda", "lg"),
	GEORGIAN("ქართული ენა", "ka"),
	GERMAN("Deutsch", "de"),
	GREEK("ελληνικά", "el"),
	KALAALLISUT("kalaallisut", "kl"),
	GUARANI("avañeʼẽ", "gn"),
	GUJARATI("ગુજરાતી", "gu"),
	HAITIAN("kreyòl ayisyen", "ht"),
	HAUSA("هَرْشَن هَوْسَ", "ha"),
	HEBREW("עִבְרִית", "he"),
	HERERO("Otjiherero", "hz"),
	HINDI("हिंदी", "hi"),
	HIRI_MOTU("Police Motu", "ho"),
	HUNGARIAN("magyar nyelv", "hu"),
	ICELANDIC("íslenska", "is"),
	IDO("Ido", "io"),
	IGBO("Ásụ̀sụ́ Ìgbò", "ig"),
	INDONESIAN("bahasa Indonesia", "id"),
	INTERLINGUA("interlingua", "ia"),
	INTERLINGUE("Interlingue", "ie"),
	INUKTITUT("ᐃᓄᒃᑎᑐᑦ", "iu"),
	INUPIAQ("Uqautchiq Iñupiatun", "ik"),
	IRISH("Gaeilge", "ga"),
	ITALIAN("italiano", "it"),
	JAPANESE("日本語", "ja"),
	JAVANESE("ꦧꦱꦗꦮ", "jv"),
	KANNADA("ಕನ್ನಡ", "kn"),
	KANURI("Kànùrí", "kr"),
	KASHMIRI("كٲشُر, कॉशुर", "ks"),
	KAZAKH("qazaqşa", "kk"),
	KHMER("ភាសាខ្មែរ", "km"),
	KIKUYU("Gĩgĩkũyũ", "ki"),
	KINYARWANDA("Rwandan", "rw"),
	KIRGHIZ("قیرغیزچا", "ky"),
	KOMI("Komi kyv", "kv"),
	KONGO("Kikongo", "kg"),
	KOREAN("한국어", "ko"),
	KWANYAMA("Oshikwanyama", "kj"),
	KURDISH("کوردی", "ku"),
	LAO("ພາສາລາວ", "lo"),
	LATIN("lingua latīna", "la"),
	LATVIAN("Lettish", "lv"),
	LIMBURGAN("Limburgan", "li"),
	LINGALA("Lingála", "ln"),
	LITHUANIAN("lietuvių kalba", "lt"),
	LUBA_KATANGA("Kiluba", "lu"),
	LUXEMBOURGISH("Lëtzebuergesch", "lb"),
	MACEDONIAN("makedonski", "mk"),
	MALAGASY("malagasy", "mg"),
	MALAY("بهاس ملايو", "ms"),
	RUMI_SCRIPT("Tulisan Rumi","ms-Latn"),
	JAWI_ALPHABET("توليسن جاوي","ms-Arab"),
	MALAYALAM("മലയാളം", "ml"),
	MALTESE("Malti", "mt"),
	MANX("Gaelg", "gv"),
	MAORI("Te reo Māori", "mi"),
	MARATHI("मराठी", "mr"),
	MARSHALLESE("Kajin M̧ajeļ", "mh"),
	MONGOLIAN("монгол хэл", ""),
	NAURU("Ekaiairũ Naoero", "na"),
	NAVAJO("Diné bizaad", "nv"),
	NORTH_NDEBELE("Zimbabwe Ndebele", "nd"),
	SOUTH_NDEBELE("Transvaal Ndebele", "nr"),
	NDONGA("ndonga", "ng"),
	NEPALI("नेपाली", "ne"),
	NORWEGIAN("norsk", "no"),
	NORWEGIAN_BOKMAL("bokmål", "nb"),
	NORWEGIAN_NYNORSK("nynorsk", "nn"),
	SICHUAN_YI("ꆈꌠꉙ", "ii"),
	OCCITAN("lenga d'òc", "oc"),
	OJIBWA("ᐊᓂᐦᔑᓈᐯᒧᐎᓐ", "oj"),
	ORIYA("ଓଡ଼ିଆ", "or"),
	OROMO("Afaan Oromoo", "om"),
	OSSETIAN("irōn ævzag", "os"),
	PALI("Pāli", "pi"),
	PASHTO("پښتو", "ps"),
	PAPIAMENTO("Papiamentu","pap"),
	PERSIAN("فارسی", "fa"),
	POLISH("polski", "pl"),
	PORTUGUESE("português", "pt"),
	PUNJABI("ਪੰਜਾਬੀ", "pa"),
	QUECHUA("Kechua", "qu"),
	ROMANIAN("limba română", "ro"),
	MOLDOVAN("limba moldoveană", "ro"),
	ROMANSH("romontsch", "rm"),
	RUNDI("Ikirundi", "rn"),
	RUSSIAN("Русский язык", "ru"),
	NORTHERN_SAMI("davvisámegiella", "se"),
	SAMOAN("Gagana faʻa Sāmoa", "sm"),
	SANGO("yângâ tî sängö", "sg"),
	SANSKRIT("संस्कृत-", "sa"),
	SARDIAN("sardu limba", "sc"),
	SERBIAN("српски језик", "sr"),
	SHONA("chiShona", "sn"),
	SINDHI("سنڌي", "sd"),
	SINHALA("සිංහල", "si"),
	SLOVAK("slovenčina", "sk"),
	SLOVENIAN("Slovenian", "sl"),
	SOMALI("صومالي", "so"),
	SOUTHERN_SOTHO("Sesotho", "st"),
	SPANISH("español", "es"),
	SUNDANESE("بَاسَا سُوْندَا", "su"),
	SWAHILI("Kiswahili", "sw"),
	SWATI("siSwati", "ss"),
	SWEDISH("svenska", "sw"),
	TAGALOG("Wikang Tagalog", "tl"),
	TAHITIAN("Reo Tahiti", "ty"),
	//TAMAZIGHT("Tamaziɣt",""),
	TAJIK("Тоҷикӣ", "tg"),
	TAMIL("தமிழ்", "ta"),
	TATAR("تاتار تلی", "tt"),
	TELUGU("తెలుగు", "te"),
	THAI("ภาษาไทย", "th"),
	TIBETAN("ལྷ་སའི་སྐད་", "bo"),
	TIGRINYA("ትግርኛ", "ti"),
	TONGA("lea faka-Tonga", "to"),
	TSONGA("Xitsonga", "ts"),
	TSWANA("Setswana", "tn"),
	TURKISH("Türkçe", "tr"),
	TURKMEN("türkmençe", "tk"),
	TWI("Akan Kasa", "tw"),
	UIGHUR("ئۇيغۇر تىلى", "ug"),
	UKRAINIAN("украї́нська мо́ва", "uk"),
	URDU("اُردُو", "ur"),
	UZBEK("Oʻzbekcha", "uz"),
	VENDA("Tshivenḓa", "ve"),
	VIETNAMESE("Tiếng Việt", "vi"),
	VOLAPUK("Volapük", "vo"),
	WALLOON("walon", "wa"),
	WELSH("Cymraeg", "cy"),
	WOLOF("ولوفل", "wo"),
	XHOSA("isiXhosa", "xh"),
	YIDDISH("ייִדיש", "yi"),
	YORUBA("Èdè Yorùbá ", "yo"),
	ZHUANG("Vahcuengh", "za"),
	ZULU("isiZulu", "zu")
}