name: Android CI

on:
  push:
    branches: [ "v0.1.28" ]
  pull_request:
    branches: [ "v0.1.28" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Decode Keystore
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
          mkdir "${GITHUB_WORKSPACE}"/app/keystore/
          echo $ENCODED_STRING | base64 -di > "${GITHUB_WORKSPACE}"/app/keystore/remember_card.jks
          
    - name: Decode GOOGLE SERVICE
      env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICE }}
      run: |
          echo $ENCODED_STRING | base64 -di > "${GITHUB_WORKSPACE}"/app/google-services.json
          
    - name: Decode KEYSTORE BKS
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BKS }}
      run: |
          mkdir "${GITHUB_WORKSPACE}"/modules/network/src/main/assets/keys
          echo $ENCODED_STRING | base64 -di > "${GITHUB_WORKSPACE}"/modules/network/src/main/assets/keys/keystore.bks
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build bundle release
      run: ./gradlew :app:bundleRelease
      
    - name: Build bundle debug
      run: ./gradlew :app:bundleDebug
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: app/build/outputs/
